# This is a basic workflow to help you get started with Actions

name: Autobuild Plugin

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop, action-test ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 15
        kotlin-version:  1.4.10
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - run: ./gradlew buildPlugin
    - uses: actions/upload-artifact@v2
      with:
        name: orion
        path: build/libs
    - name: Plugin compatibility
    - uses: thepieterdc/intellij-plugin-verifier-action@v1.3.0
      with:
        plugin: '/home/runner/work/demo-plugin/demo-plugin/build/distributions/demo-plugin-*'
        versions: |
          LATEST
