# This is a basic workflow to help you get started with Actions

name: Autobuild and validate Plugin

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop, action-test-1 ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - run: ./gradlew buildPlugin
    - uses: actions/upload-artifact@v2
      with:
        name: orion
        path: build/libs
    - name: IntelliJ Plugin Verifier
      uses: thepieterdc/intellij-plugin-verifier-action@1.3.0      
      with:
        plugin: 'build/libs/orion.zip'
        versions: |
          2020.3
